In [3]:
#Lists

In [4]:
mylist = ['hi', 55, 2.1]

In [5]:
mylist

['hi', 55, 2.1]

In [6]:
l2 = ['yo', mylist]

In [7]:
l2

['yo', ['hi', 55, 2.1]]

---

In [8]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
z = list(range(100,120))

In [10]:
print(z)

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]


In [11]:
y = list(range(100,120,3))

In [12]:
y

[100, 103, 106, 109, 112, 115, 118]

In [13]:
y[3]

109

In [14]:
x = [1,2,3]
x

[1, 2, 3]

In [15]:
x[-2]

2

In [16]:
x[-1]

3

In [17]:
x[2] = y

In [18]:
x

[1, 2, [100, 103, 106, 109, 112, 115, 118]]

In [19]:
y[1] = 'DD'

In [20]:
x

[1, 2, [100, 'DD', 106, 109, 112, 115, 118]]

In [21]:
y

[100, 'DD', 106, 109, 112, 115, 118]

In [22]:
print(y[2:5])

[106, 109, 112]


In [23]:
print(y[:5])

[100, 'DD', 106, 109, 112]


In [24]:
y

[100, 'DD', 106, 109, 112, 115, 118]

In [25]:
y.append('GG')

In [26]:
y

[100, 'DD', 106, 109, 112, 115, 118, 'GG']

In [27]:
y.insert(3,69)

In [28]:
y

[100, 'DD', 106, 69, 109, 112, 115, 118, 'GG']

In [29]:
x

[1, 2, [100, 'DD', 106, 69, 109, 112, 115, 118, 'GG']]

In [30]:
y

[100, 'DD', 106, 69, 109, 112, 115, 118, 'GG']

In [31]:
y[2:7:2]

[106, 109, 115]

In [32]:
y

[100, 'DD', 106, 69, 109, 112, 115, 118, 'GG']

In [33]:
y[-8:6]

['DD', 106, 69, 109, 112]

In [34]:
y

[100, 'DD', 106, 69, 109, 112, 115, 118, 'GG']

In [35]:
y[::-1]

['GG', 118, 115, 112, 109, 69, 106, 'DD', 100]

In [36]:
y[::-2]

['GG', 115, 109, 106, 100]

---

In [37]:
y

[100, 'DD', 106, 69, 109, 112, 115, 118, 'GG']

In [38]:
y[6:1:-1]

[115, 112, 109, 69, 106]

In [39]:
#TUPLES

In [40]:
t1 = (123,55,69)

In [41]:
t1

(123, 55, 69)

---

In [42]:
#ARRAYS

In [43]:
import numpy as np

In [49]:
l = [1,2,3,4,5,6]

In [50]:
az = np.array(l)

In [51]:
az

array([1, 2, 3, 4, 5, 6])

In [52]:
y

[100, 'DD', 106, 69, 109, 112, 115, 118, 'GG']

In [53]:
arr

array(['100', 'DD', '106', '69', '109', '112', '115', '118', 'GG'],
      dtype='<U11')

In [54]:
print(arr)

['100' 'DD' '106' '69' '109' '112' '115' '118' 'GG']


In [57]:
az.mean()

3.5

In [58]:
az

array([1, 2, 3, 4, 5, 6])

In [73]:
 g = [True, 55]

In [74]:
gg = np.array(g)
print(gg)

[ 1 55]


---

In [75]:
#SLICING ARRAYS

In [76]:
az[2:]

array([3, 4, 5, 6])

In [77]:
az[2:4]

array([3, 4])

In [78]:
b = az[2:4]

In [79]:
b

array([3, 4])

In [80]:
b[:] = 111

In [81]:
b

array([111, 111])

In [82]:
az

array([  1,   2, 111, 111,   5,   6])

In [83]:
c = az.copy()

In [84]:
c

array([  1,   2, 111, 111,   5,   6])

In [85]:
c[0]=123

In [86]:
c

array([123,   2, 111, 111,   5,   6])

In [87]:
az

array([  1,   2, 111, 111,   5,   6])